version: '3.4'

services: 
    java:
        build: 
            context: .
        tty: true
        restart: always
        volumes: 
            - ./:/myapp
            - ./.docker/sdk:/root/.m2
        networks: 
            - udemy-networks
        environment: 
            TZ: America/Sao_Paulo
            SPRING_BOOT_ENVIRONMENT: Production
        ports: 
            - 8080:8080
        
        command: 
            mvn clean spring-boot:run 

        
        
        depends_on: 
            - db

    db:
        image: mysql:5
        networks: 
            - udemy-networks
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: rest_api
        volumes: 
            - ./.docker/mysql:/var/lib/mysql
        ports: 
            - 3606:3606
        

    adminer:
        image: adminer
        restart: always
        links: 
            - db
        ports:
            - 8082:8080
        networks: 
            - udemy-networks


networks: 
    udemy-networks:
        driver: bridge